version: "3.8"

networks:
  local:

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - app1
      - app2
    networks:
      - local

  app1:
    build: ./app
    hostname: app1
    networks:
      - local

  app2:
    build: ./app
    hostname: app2
    networks:
      - local
